# Generated by Django 5.2.3 on 2025-06-23 07:08

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(choices=[('nda', 'NDA'), ('invoice', 'Invoice'), ('offer', 'Offer Letter')], max_length=20)),
                ('plain_pdf', models.FileField(upload_to='documents/plain/')),
                ('encrypted_pdf', models.FileField(upload_to='documents/encrypted/')),
                ('encrypted_metadata', django_cryptography.fields.encrypt(models.JSONField(blank=True, null=True))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
