# Generated by Django 5.2.3 on 2025-06-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='encrypted_html',
            field=models.FileField(blank=True, null=True, upload_to='documents/encrypted_html/'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='plain_html',
            field=models.FileField(blank=True, null=True, upload_to='documents/plain_html/'),
        ),
    ]
