# Generated by Django 5.2.3 on 2025-06-23 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_pdf', models.FileField(upload_to='documents/signed/')),
                ('signed_encrypted_pdf', models.FileField(upload_to='documents/signed_encrypted/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('original_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signed_version', to='documents.generateddocument')),
            ],
        ),
    ]
